#!/usr/bin/env python3
"""mora-pod-scaffold — first-time setup for an agent pod's /work directory.

Usage (inside the pod):
    mora-pod-scaffold --role manager
    mora-pod-scaffold --role developer --force   # overwrite existing files

What it writes (under /work):
    .env                            MORA_KNODE_API / AGENT_ID / TOKEN / ROLE
    .claude/agents/<role>.md        copied from /opt/mora-knode-context/
                                    sub-agent-templates/<role>.md, with
                                    {{ROLE}} / {{API}} placeholders filled
    crewai-recipe/                  copy of the CrewAI starting recipe
    README-pod.md                   short next-step note

Inputs:
    --role            manager | developer | researcher | qa  (default from
                      $MORA_KNODE_AGENT_ROLE, falls back to 'developer')
    --token           default $MORA_KNODE_AGENT_TOKEN
    --agent-id        default $MORA_KNODE_AGENT_ID
    --base-url        default $MORA_KNODE_API or http://localhost:5163
    --force           overwrite existing files in /work

The script is intentionally idempotent-by-default: it skips any file that
already exists unless --force is passed, so re-running it after the
operator has tweaked /work doesn't clobber their changes.
"""
from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

CONTEXT_ROOT = Path("/opt/mora-knode-context")
WORK_ROOT = Path("/work")
ROLES = {"manager", "developer", "researcher", "qa"}


def fill(text: str, role: str, base_url: str, agent_id: str) -> str:
    return (
        text.replace("{{ROLE}}", role)
        .replace("{{API}}", base_url)
        .replace("{{AGENT_ID}}", agent_id)
    )


def write(path: Path, content: str, *, force: bool) -> str:
    if path.exists() and not force:
        return f"skip  {path}  (exists; pass --force to overwrite)"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return f"write {path}"


def copy_tree(src: Path, dst: Path, *, force: bool) -> str:
    if dst.exists() and not force:
        return f"skip  {dst}  (exists; pass --force to overwrite)"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    return f"copy  {src} -> {dst}"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--role", default=os.environ.get("MORA_KNODE_AGENT_ROLE", "developer"))
    p.add_argument("--token", default=os.environ.get("MORA_KNODE_AGENT_TOKEN", ""))
    p.add_argument("--agent-id", default=os.environ.get("MORA_KNODE_AGENT_ID", ""))
    p.add_argument("--base-url", default=os.environ.get("MORA_KNODE_API", "http://localhost:5163"))
    p.add_argument("--force", action="store_true")
    args = p.parse_args()

    role = args.role.lower()
    if role not in ROLES:
        print(f"error: --role must be one of {sorted(ROLES)}, got {role!r}", file=sys.stderr)
        return 2
    if not args.token or not args.agent_id:
        print(
            "warning: token / agent-id are blank; .env will be a stub. Re-run "
            "with --token / --agent-id set or with the env vars exported.",
            file=sys.stderr,
        )

    if not CONTEXT_ROOT.exists():
        print(f"error: context dir {CONTEXT_ROOT} not found inside this image", file=sys.stderr)
        return 2

    WORK_ROOT.mkdir(parents=True, exist_ok=True)

    # 1. .env
    env_text = (
        f"# Generated by mora-pod-scaffold for role={role}\n"
        f"MORA_KNODE_API={args.base_url}\n"
        f"MORA_KNODE_AGENT_ID={args.agent_id}\n"
        f"MORA_KNODE_AGENT_TOKEN={args.token}\n"
        f"MORA_KNODE_AGENT_ROLE={role}\n"
    )
    print(write(WORK_ROOT / ".env", env_text, force=args.force))

    # 2. .claude/agents/<role>.md
    template = CONTEXT_ROOT / "sub-agent-templates" / f"{role}.md"
    if template.exists():
        filled = fill(template.read_text(encoding="utf-8"), role, args.base_url, args.agent_id)
        print(write(WORK_ROOT / ".claude" / "agents" / f"{role}.md", filled, force=args.force))
    else:
        print(f"warn  no sub-agent template for role={role!r} at {template}", file=sys.stderr)

    # 3. CrewAI recipe (copy whole dir)
    recipe_src = CONTEXT_ROOT / "crewai-recipe"
    if recipe_src.exists():
        print(copy_tree(recipe_src, WORK_ROOT / "crewai-recipe", force=args.force))

    # 4. README-pod.md
    readme = (
        f"# Pod ({role})\n\n"
        f"Talking to mora-knode at **{args.base_url}** as agent "
        f"`{args.agent_id or '(unset)'}`.\n\n"
        f"## Next\n\n"
        f"1. Install your paired LLM CLI:\n"
        f"   ```\n"
        f"   npm install -g @anthropic-ai/claude-code   # Claude Pro\n"
        f"   npm install -g @openai/codex                # ChatGPT Pro\n"
        f"   ```\n"
        f"2. Read the API reference: `/opt/mora-knode-context/api-reference.md`\n"
        f"3. Read the workflow guide: `/opt/mora-knode-context/workflow-guide.md`\n"
        f"4. Tweak `.claude/agents/{role}.md` for your operating preferences.\n"
        f"5. Or run the CrewAI recipe directly:\n"
        f"   ```\n"
        f"   cd /work/crewai-recipe && python main.py\n"
        f"   ```\n"
    )
    print(write(WORK_ROOT / "README-pod.md", readme, force=args.force))

    print()
    print(f"done. /work is set up for role={role!r}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
